#This is the name of the workflow that will be displayed in the action tab

name: CICD

#Manual click deliver workflow whenever user needs
on:
  workflow_dispatch:

jobs:

  code:
     runs-on: ubuntu-latest
     steps:
        - name: chekout code
          run: echo "Code Clone from GitHub"
        
  build:
       runs-on: ubuntu-latest
       steps:
         - name: Build Docker container
           run: echo "Docker container build"

  test:
       runs-on: ubuntu-latest
       steps:
         - name: test the container
           run: echo "testing the container"

  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: deploy the app
          run: echo "Docker compose deployed the app"
        - name: Deploying the app
          run: echo "Docker compose deployed the app"
      
